project_id = "ctchkdgmlcbuobzqyams"

[functions.google-sheets-sync]
verify_jwt = true

[functions.google-auth]
verify_jwt = false

[functions.google-sheets-list]
verify_jwt = false

[functions.google-sheets-private-sync]
verify_jwt = false

[functions.meta-sync]
verify_jwt = true

[functions.member-meta-setup]
verify_jwt = true

[functions.meta-campaigns-live]
verify_jwt = true

[functions.tiktok-sync]
verify_jwt = true

[functions.tiktok-campaigns-live]
verify_jwt = true

[functions.member-tiktok-setup]
verify_jwt = true

[functions.send-campaign-email]
verify_jwt = true

[functions.invite-handler]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.create-topup-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-wallet-balance]
verify_jwt = true
